<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>plasmapper</Authors>
    <Description>BlackBox library for .NET</Description>
    <Copyright>Copyright (c) plasmapper 2024</Copyright>
    <PackageProjectUrl>https://github.com/plasmapper/blackbox-dotnet</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/plasmapper/blackbox-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags></PackageTags>
    <PackageReleaseNotes>Added
- Async support.
- Index property to IHardwareInterface and IServer.
- Messages to NotSupportedException thrown by IHardwareInterface and IServer setters not applicable to the current type

Changed
- ModbusClient constructors to match those of PL.Modbus.Client.
- Configuration and state properties to be null if not applicable.
- IClient, IHardwareInterface and IServer members exception documentation.
- Modbus addresses to named constants.

Fixed
- Wrong IPv6 address returned by SetIpV6GlobalAddress.
- Hardware interface/server index out of range exception type.
- Unclear exception when SetDeviceName, SetWiFiSsid or SetWiFiPassword value is too long.
- Silent corruption of non-ASCII characters in SetDeviceName, SetWiFiSsid and SetWiFiPassword values.</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <VersionPrefix>2.0.0</VersionPrefix>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<DebugType>none</DebugType>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageOutputPath>../../build</PackageOutputPath>
	</PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PL.Modbus" Version="3.1.1" />
  </ItemGroup>

</Project>
